### ISSUE TITLE
这个可以过度到ionic3嘛

### ISSUE THREAD

**Issue by zhuqiyun** [yanxiaojun617/ionic2_wx#1]
这个可以过度到ionic3嘛

**Comment by xiaosan666** [comment]
已经是ionic3了，ionic2和3是一样的

**Comment by xiaosan666** [comment]
https://github.com/yanxiaojun617/ionic2_wx/blob/master/package.json

**Comment by zhuqiyun** [comment]
谢谢   准备在实际项目中应用看看
